### PR TITLE
Make DCO Verification optional.

### PR DESCRIPTION
**Pull request by rosswhitfield**
This adds the DCO verification as an option in the config.json. Very few projects require this.

### CODE REVIEW

**Comment by calavera** [comment]
Actually, every Docker project should require this for legal reasons. But, for now, it's only enforced in docker/docker.

**Comment by rosswhitfield** [comment]
I was thinking for people outside of docker who wanted to use leeroy for their own projects. Until recently leeroy didn't have anything docker specific in it and was just a nice port with a few extra features, it would be nice if it could still function that way.

**Comment by emanuelez** [comment]
This looks like a must-have for non-docker projects. Please rebase/merge with master and review :)

**Comment by rosswhitfield** [comment]
Unfortunately it appears that they have no interest in supporting leeroy for anything except docker. They have added even more non-optional docker only 'features' (like the labels) that makes it unusable for any other projects. I forked it as the last good point and that's what I'm using.

**Comment by jfrazelle** [comment]
Sorry we can't win em all, hope you can understand this isn't my main focus, and we need what we need to work for now :/






On Wed, Aug 26, 2015 at 6:22 AM -0700, "Ross Whitfield" <notifications@github.com> wrote:












Unfortunately it appears that they have no interest in supporting leeroy for anything except docker. They have added even more non-optional docker only 'features' (like the labels) that makes it unusable for any other projects. I forked it as the last good point and that's what I'm using.

**Comment by jfrazelle** [comment]
No one is perfect :p






On Wed, Aug 26, 2015 at 6:22 AM -0700, "Ross Whitfield" <notifications@github.com> wrote:












Unfortunately it appears that they have no interest in supporting leeroy for anything except docker. They have added even more non-optional docker only 'features' (like the labels) that makes it unusable for any other projects. I forked it as the last good point and that's what I'm using.

**Pull request closed without merging**
