### PR TITLE
Fix copy-pasta typo

### PR DESCRIPTION
**Pull request by thaJeztah**
ref https://github.com/docker/leeroy/pull/44#discussion_r50315641

/cc @runcom @vdemeester :dancer:

### CODE REVIEW

**Comment by jfrazelle** [comment]
nice

**Comment by jfrazelle** [comment]
sorry

**Comment by thaJeztah** [comment]
Oh why the "sorry"? :D

**Comment by jfrazelle** [comment]
because i think i merged too quick before hahaha, unless you caught it
after merge

**Comment by vdemeester** [comment]
@jfrazelle *caught it* after the merge, that's my bad :stuck_out_tongue_closed_eyes:

**Pull request merged**
