### PR TITLE
Do not build PRs with only docs.

### PR DESCRIPTION
**Pull request by calavera**
- Avoid loading the PR content twice (reduce requests to the GitHub API)

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by jfrazelle** [comment]
ok buttttttt I dont want this because i want to evtually run seperate tests for docs ;)

**Comment by calavera** [comment]
I totally agree with you, but we can revisit that when we have those tests. Besides, running specific builds only for docs will be easier after this change, I think, because we'll already have the code to differentiate docs build vs code build in place.

**Comment by thaJeztah** [comment]
@calavera build failed; 

```
go build -v returned exit code 2

./handlers.go:208: g.LoadPullRequest undefined (type github.GitHub has no field or method LoadPullRequest) Action failed: go build
```

**Comment by calavera** [comment]
no idea why. That method is definitely in the right place:
```
calavera@d ~/dev/src/github.com/jfrazelle/leeroy (do_not_build_docs_only)$ go build -v
github.com/crosbymichael/octokat
github.com/jfrazelle/leeroy/jenkins
github.com/jfrazelle/leeroy/github
github.com/jfrazelle/leeroy
calavera@d ~/dev/src/github.com/jfrazelle/leeroy (do_not_build_docs_only●)$ ls leeroy
leeroy
```

**Comment by jfrazelle** [comment]
imm rebuilding

**Comment by calavera** [comment]
:tada:

**Pull request merged**
